import os
import sys
from pathlib import Path

PLUGIN_DIR = Path(__file__).parent
ENABLED_FILE = PLUGIN_DIR / "ENABLED"
DEPENDENCIES = ["xhtml2pdf"]

def export_pdf(content_html, output_path, meta):
    """
    Export content to PDF using xhtml2pdf.
    """
    try:
        from xhtml2pdf import pisa
        
        # We need to ensure images are handled correctly
        # xhtml2pdf needs absolute paths or access to static files
        
        # Prepare content with some basic styling for PDF
        # We inject a print-specific CSS
        full_html = f"""
        <html>
        <head>
            <style>
                @page {{
                    size: A4;
                    margin: 1cm;
                    @frame footer_frame {{
                        -pdf-frame-content: footerContent;
                        bottom: 0cm;
                        margin-left: 1cm;
                        margin-right: 1cm;
                        height: 1cm;
                    }}
                }}
                body {{ font-family: Helvetica, sans-serif; font-size: 10pt; }}
                h1 {{ color: #1a56db; border-bottom: 2px solid #1a56db; padding-bottom: 5px; }}
                h2 {{ color: #374151; margin-top: 20px; }}
                code {{ background-color: #f3f4f6; padding: 2px 4px; border-radius: 4px; font-family: Courier; }}
                pre {{ background-color: #1f2937; color: #f9fafb; padding: 10px; border-radius: 8px; white-space: pre-wrap; }}
                img {{ max-width: 100%; height: auto; }}
                blockquote {{ border-left: 4px solid #e5e7eb; padding-left: 10px; color: #6b7280; }}
            </style>
        </head>
        <body>
            {content_html}
            <div id="footerContent" style="text-align:right; color: #9ca3af; font-size: 8pt;">
                Generated by DocNexus
            </div>
        </body>
        </html>
        """
        
        with open(output_path, "wb") as pdf_file:
            pisa_status = pisa.CreatePDF(
                full_html,              # the HTML to convert
                dest=pdf_file           # file handle to recieve result
            )
            
        if pisa_status.err:
            raise RuntimeError(f"PDF generation error: {pisa_status.err}")
            
        return True
        
    except ImportError:
        raise RuntimeError("xhtml2pdf library is missing. Please reinstall DocNexus or check dependencies.")
    except Exception as e:
        raise RuntimeError(f"PDF Export Failed: {e}")

def get_features():
    from docnexus.features.registry import Feature, FeatureType, FeatureState
    
    # Check "Enabled" status via marker file
    is_enabled = ENABLED_FILE.exists()
    
    features = []
    
    # We register the feature but mark it as installed/not installed
    # If not installed, the UI shows "Install".
    # Logic in app.py uses this 'installed' meta.
    
    features.append(
        Feature(
            "pdf_export",
            feature_type=FeatureType.EXPORT_HANDLER,
            handler=export_pdf,
            state=FeatureState.BETA,
            meta={
                "extension": "pdf",
                "label": "PDF Document (.pdf)",
                "installed": is_enabled,
                "description": "Generates professional PDF documents from your markdown.",
                "version": "1.0.0"
            }
        )
    )
    
    return features
